### ISSUE TITLE
Getting request data from RawRequest fails

### ISSUE THREAD

**Issue by TDabasinskas** [Crypt32/PSPKI#6]
Hi,

I need to extract DNS data from a pending request, as shown in [this article](https://www.sysadmins.lv/blog-en/manage-pending-certificate-requests-in-adcs-with-powershell.aspx).

Anyhow, doing the following while using the latest module version fails for me:
```powershell
$row = Get-PendingRequest -CA CANAME -Property "RawRequest" -Request;
$bytes = [convert]::FromBase64String($row."Request.RawRequest");
New-Object System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest (,$bytes)
```
with the following error:
```
New-Object : Exception calling ".ctor" with "1" argument(s): "Object reference not set to an instance of an object."
```
I get the exact same error if, instead of manually creating `X509CertificateRequest`, I use the following:
```powershell
Get-CertificateRequest -RawRequest $bytes
```
Is it a known issue or I'm doing something wrong?

**Comment by Crypt32** [comment]
Can you post StackTrace of the error?

**Comment by TDabasinskas** [comment]
Trying this:
```powershell
Get-CertificateRequest -RawRequest ([convert]::FromBase64String(((Get-CertificationAuthority -ComputerName ([System.Net.Dns]::GetHostByName(($ENV:COMPUTERNAME))).HostName | Get-PendingRequest -Property * | Select-Object 'Request.RawRequest'))[0].'Request.RawRequest')); $Error | Select-Object * | Set-Clipboard
```
Getting this:
```
@{PSMessageDetails=; Exception=System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Object reference not set to an instance of an object." ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest.decodePkcs7()
   --- End of inner exception stack trace ---
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args); TargetObject=; CategoryInfo=InvalidOperation: (:) [New-Object], MethodInvocationException; FullyQualifiedErrorId=ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Get-CertificateRequest, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Client\Get-CertificateRequest.ps1: line 22
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
@{PSMessageDetails=; Exception=System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Object reference not set to an instance of an object." ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest.decodePkcs7()
   --- End of inner exception stack trace ---
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args); TargetObject=; CategoryInfo=InvalidOperation: (:) [New-Object], MethodInvocationException; FullyQualifiedErrorId=ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Get-CertificateRequest, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Client\Get-CertificateRequest.ps1: line 22
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
@{PSMessageDetails=; Exception=System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Object reference not set to an instance of an object." ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest.decodePkcs7()
   --- End of inner exception stack trace ---
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args); TargetObject=; CategoryInfo=InvalidOperation: (:) [New-Object], MethodInvocationException; FullyQualifiedErrorId=ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Get-CertificateRequest, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Client\Get-CertificateRequest.ps1: line 22
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
@{PSMessageDetails=; Exception=System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Object reference not set to an instance of an object." ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest.decodePkcs7()
   --- End of inner exception stack trace ---
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args); TargetObject=; CategoryInfo=InvalidOperation: (:) [New-Object], MethodInvocationException; FullyQualifiedErrorId=ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Get-CertificateRequest, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Client\Get-CertificateRequest.ps1: line 22
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
@{PSMessageDetails=; Exception=System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Object reference not set to an instance of an object." ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest.decodePkcs7()
   --- End of inner exception stack trace ---
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args); TargetObject=; CategoryInfo=InvalidOperation: (:) [New-Object], MethodInvocationException; FullyQualifiedErrorId=ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Get-CertificateRequest, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Client\Get-CertificateRequest.ps1: line 22
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
@{PSMessageDetails=; Exception=System.ArgumentException: CCertView::GetColumnIndex: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)
   at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
   at CallSite.Target(Closure , CallSite , ComObject , Boolean , Object )
   at Get-RequestRow(Closure , FunctionContext ); TargetObject=; CategoryInfo=OperationStopped: (:) [], ArgumentException; FullyQualifiedErrorId=System.ArgumentException; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Get-RequestRow, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Server\Get-RequestRow.ps1: line 36
at Get-IssuedRequest<Process>, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Server\Get-IssuedRequest.ps1: line 29
at Get-CertificationAuthority, C:\Program Files\Sysadmins LV\PowerShell\Modules\PSPKI\Server\Get-CertificationAuthority.ps1: line 14
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
@{Errors=; Message=The string is missing the terminator: '.; ErrorRecord=The string is missing the terminator: '.; StackTrace=   at System.Management.Automation.AutomationEngine.ParseScriptBlock(String script, String fileName, Boolean interactiveCommand)
   at System.Management.Automation.Runspaces.Command.CreateCommandProcessor(ExecutionContext executionContext, CommandFactory commandFactory, Boolean addToHistory, CommandOrigin origin)
   at System.Management.Automation.Runspaces.LocalPipeline.CreatePipelineProcessor()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc(); WasThrownFromThrowStatement=False; Data=System.Collections.ListDictionaryInternal; InnerException=; TargetSite=System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable); HelpLink=; Source=System.Management.Automation; HResult=-2146233087}
@{Errors=System.Management.Automation.Language.ParseError[]; Message=At line:1 char:507
+ ... UeofveYUW4HTOrY0K76JJqwkzRO5Qc93H9jybpNAcm+3GssfwKG7SoHfwW5BQIDAQAB')
+                                                                         ~
Unexpected token ')' in expression or statement.; ErrorRecord=At line:1 char:507
+ ... UeofveYUW4HTOrY0K76JJqwkzRO5Qc93H9jybpNAcm+3GssfwKG7SoHfwW5BQIDAQAB')
+                                                                         ~
Unexpected token ')' in expression or statement.; StackTrace=   at System.Management.Automation.AutomationEngine.ParseScriptBlock(String script, String fileName, Boolean interactiveCommand)
   at System.Management.Automation.Runspaces.Command.CreateCommandProcessor(ExecutionContext executionContext, CommandFactory commandFactory, Boolean addToHistory, CommandOrigin origin)
   at System.Management.Automation.Runspaces.LocalPipeline.CreatePipelineProcessor()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc(); WasThrownFromThrowStatement=False; Data=System.Collections.ListDictionaryInternal; InnerException=; TargetSite=System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable); HelpLink=; Source=System.Management.Automation; HResult=-2146233087}
@{PSMessageDetails=; Exception=System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'Table'. Cannot convert value "Request-Property" to type "PKI.CertificateServices.DB.TableList". Error: "Unable to match the identifier name Request-Property to a valid enumerator name. Specify one of the following enumerator names and try again:
Request, Extension, Attribute, CRL" ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value "Request-Property" to type "PKI.CertificateServices.DB.TableList". Error: "Unable to match the identifier name Request-Property to a valid enumerator name. Specify one of the following enumerator names and try again:
Request, Extension, Attribute, CRL" ---> System.Management.Automation.PSInvalidCastException: Cannot convert value "Request-Property" to type "PKI.CertificateServices.DB.TableList". Error: "Unable to match the identifier name Request-Property to a valid enumerator name. Specify one of the following enumerator names and try again:
Request, Extension, Attribute, CRL" ---> System.Management.Automation.RuntimeException: Unable to match the identifier name Request-Property to a valid enumerator name. Specify one of the following enumerator names and try again:
Request, Extension, Attribute, CRL
   at System.Management.Automation.EnumMinimumDisambiguation.EnumDisambiguate(String text, Type enumType)
   at System.Management.Automation.LanguagePrimitives.ConvertStringToEnum(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   --- End of inner exception stack trace ---
   at System.Management.Automation.LanguagePrimitives.ConvertStringToEnum(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame); TargetObject=; CategoryInfo=InvalidData: (:) [Get-DatabaseRow], ParameterBindingArgumentTransformationException; FullyQualifiedErrorId=ParameterArgumentTransformationError,Get-DatabaseRow; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
@{writeErrorStream=True; PSMessageDetails=; Exception=System.IO.FileNotFoundException: The specified module 'PSReadline' was not loaded because no valid module file was found in any module directory.; TargetObject=PSReadline; CategoryInfo=ResourceUnavailable: (PSReadline:String) [Import-Module], FileNotFoundException; FullyQualifiedErrorId=Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand; ErrorDetails=; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
```

**Comment by Crypt32** [comment]
Sorry, I forgot to mention that I need stack trace from inner exception: `$error[0].Exception.InnerException.StackTrace`.

**Comment by TDabasinskas** [comment]
The only thing it outputs is:

```
   at System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest.decodePkcs7()
```

**Comment by Crypt32** [comment]
I'll take a look into this.

**Comment by EpicPhil** [comment]
Any update on this? I'm experiencing the same issue on 3.2.7.0.

**Comment by Crypt32** [comment]
Sorry, I have no progress on this due to a lack of repro material. Can you, please, provide sample request? If it contains sensitive information, you can send request via email to me and I will work privately.

**Comment by EpicPhil** [comment]
I can't send you anything, but I can reliably get the error with the following code snippet. I'm trying to find a pattern in which requests produce the error, because not all of them do. 

```powershell
$revoked = Get-RevokedRequest -CertificationAuthority $CA -Property RawRequest | select -Last 25
foreach ($req in $revoked) {
    $bytes = [convert]::FromBase64String($req.'Request.RawRequest')
    Write-Output "RequestId: $($req.RequestId)"
    New-Object System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest (,$bytes)
}
```

**Comment by Crypt32** [comment]
Can you post full error details?
```
$error[0].Exception.InnerException.psbase
$error[0].Exception.InnerException.StackTrace
```
Is it `NullReferenceException`?

**Comment by EpicPhil** [comment]
```powershell
PS C:\Scripts> $error[0]
Exception calling ".ctor" with "1" argument(s): "Object reference not set to an 
instance of an object."
At line:5 char:5
+     [System.Security.Cryptography.X509CertificateRequests.X509Certifi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
 

PS C:\Scripts> $error[0].Exception.InnerException.psbase


Message        : Object reference not set to an instance of an object.
Data           : {}
InnerException : 
TargetSite     : Void decodePkcs7()
StackTrace     :    at System.Security.Cryptography.X509CertificateRequests.X509
                 CertificateRequest.decodePkcs7()
                    at CallSite.Target(Closure , CallSite , Type , Object )
HelpLink       : 
Source         : PKI.Core
HResult        : -2147467261




PS C:\Scripts> $error[0].Exception.InnerException.StackTrace
   at System.Security.Cryptography.X509CertificateRequests.X509CertificateRequest
.decodePkcs7()
   at CallSite.Target(Closure , CallSite , Type , Object )
```

**Comment by Crypt32** [comment]
It seems I found the issue. At some points I'm accessing request collection which is not yet initialized, because requests are not presented. This happens with CMC requests. I changed initializers to instantiate collections even if they are empty.

**Comment by Crypt32** [comment]
I hope I fixed it here: https://github.com/Crypt32/pkix.net/commit/ca7b65d9ab4057e6642df0f35f20b3927db9afdd
