### ISSUE TITLE
Get-CertificationAuthority produces System.IO.IOException: The network path was not found.

### ISSUE THREAD

**Issue by joshcorr** [Crypt32/PSPKI#65]
I found issue #25 and tried several of the steps outlined there for troubleshooting. I have two CA enviroments in two seperate forests (test and prod). Both had issue. Here are some masked results. Both CAs are running on Server 2016. 

```
[PKI.CertificateServices.CertificateAuthority]::ping("domain1.test.ad")
True
```
```
PS C:\WINDOWS\system32> $CertAdmin = new-object -com certificateauthority.admin
PS C:\WINDOWS\system32> $CertAdmin.GetCAProperty("domain1.test.ad\TestCA", 0xb, 0, 1, 0)
4
```

Full Exception when running `Get-CertificationAuthority -Computer Domain1.test.ad` 
```
System.Management.Automation.MethodInvocationException: Exception calling "EnumEnterpriseCAs" with "2" ar
" ---> System.IO.IOException: The network path was not found.

   at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView v
   at PKI.Utils.CryptoRegistry.GetRReg(String entry, String caName, String computerName, String node)
   at PKI.CertificateServices.CertificateAuthority.getType()
   at PKI.CertificateServices.CertificateAuthority.initialize()
   at PKI.CertificateServices.CertificateAuthority.EnumEnterpriseCAs(String findType, String findValue)
   at CallSite.Target(Closure , CallSite , Type , String , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exce
Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Type , String , String )
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame
```

**Comment by Crypt32** [comment]
Can you provide a stack trace from an inner exception?

**Comment by joshcorr** [comment]
So this is pretty crazy, but after sending that stack trace I ended up doing some more testing with ProcessMonitor to see what was going on with the registry key being read from, and it was correctly reading the value, but the **value was incorrect**. Apparently the CA (both prod and test) had been migrated from an old server name to the current one(s) and everything had been updated except for the registry key:
`HKLM\System\CurrentControlSet\Services\Certsvc\Configuration\TestCA\CAServerName` 

After changing this value with the following the cmdlet started working.
`certutil.exe -setreg TestCA\CAServerName domain1.test.ad`

Any chance the exception thrown by the PKI.Utils.CryptoRegistry.GetRReg could include any vales retrieved? or maybe a more helpful error message on Get-CertifcationAuthority?

**Comment by Crypt32** [comment]
I understand this issue. I think, I don't need to rely on `CAServerName` reg value when accessing Enterprise CAs and use value retrieved via `ICertConfig` interface. Can you open a separate issue that will include what I suggested in this post? This case is not an issue, it is a misconfiguration at client end. In order to avoid such incidents further, we need to describe specific issue which is `CAServerName` value retrievel from Enterprise CAs. This value makes sense only for Standalone CAs.

**Comment by joshcorr** [comment]
Okay, I will close this and create a new issue with the information above.
